### ISSUE TITLE
Support for 3D Secure and Server to Server protocol

### ISSUE THREAD

**Issue by denistorresan** [SimoTod/omnipay-setefi#1]
Hello @SimoTod,
we're developing a website that needs Server to Server and 3D Secure implementation of SETEFI payment.

I see that this plugin only support the external payments, so I think the best way is to clone the repo and add also that implementation on the same plugin, in order to have this bundle completed with also this option.

Are you interested?

Best regards!
Denis

**Comment by SimoTod** [comment]
HI @denistorresan,
forks and PR are always welcome. Fell free to clone the repo, add all the needed features and, if you like, submit a PR. Please take a look in http://omnipay.thephpleague.com/ to see how they suggest to implement the payment process
Kind regards,
Simone
